config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/I2PC/scipion-docker:
      branch: ibergrid22
      repo: https://github.com/I2PC/scipion-docker.git
    github.com/scipion-em/docs:
      branch: ibergrid22
      repo: https://github.com/scipion-em/docs.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/I2PC/scipion-docker git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-mauve-dane.sh
        container: qc.acc_skinny-thistle-moth
  QC.Doc:
    repos:
      github.com/scipion-em/docs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-burgundy-squid.sh
        container: qc.doc_beady-cobalt-stoat
      github.com/scipion-em/docs git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-xanthic-wolfhound.sh
        container: qc.doc_squeaky-cerise-armadillo
      github.com/scipion-em/docs markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-persimmon-akita.sh
        container: qc.doc_stuffy-lime-stoat
      github.com/scipion-em/docs restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-mustard-bee.sh
        container: qc.doc_skinny-jade-barnacle
  QC.Lic:
    repos:
      github.com/I2PC/scipion-docker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-sapphire-bordeaux.sh
        container: qc.lic_lumpy-tomato-spitz
  QC.Sty:
    repos:
      github.com/I2PC/scipion-docker hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-buff-tetra.sh
        container: qc.sty_skanky-maroon-avocet
  QC.Ver:
    repos:
      github.com/I2PC/scipion-docker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-grey-antelope.sh
        container: qc.ver_paltry-corn-badger
timeout: 1800
