config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/I2PC/scipion-docker:
      branch: ibergrid22
      repo: https://github.com/I2PC/scipion-docker.git
    github.com/scipion-em/docs:
      branch: ibergrid22
      repo: https://github.com/scipion-em/docs.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/I2PC/scipion-docker git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-malachite-audemer.sh
        container: qc.acc_scummy-ruby-falcon
  QC.Doc:
    repos:
      github.com/scipion-em/docs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-corn-robin.sh
        container: qc.doc_smelly-olive-dhole
      github.com/scipion-em/docs git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-razzmatazz-tiger.sh
        container: qc.doc_woozy-amber-dhole
      github.com/scipion-em/docs restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-smalt-fousek.sh
        container: qc.doc_ready-chartreuse-echidna
  QC.Lic:
    repos:
      github.com/I2PC/scipion-docker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-malachite-squirrel.sh
        container: qc.lic_nerdy-corn-bat
  QC.Sty:
    repos:
      github.com/I2PC/scipion-docker hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-apricot-goat.sh
        container: qc.sty_jumpy-orange-quetzal
  QC.Ver:
    repos:
      github.com/I2PC/scipion-docker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-silver-blue.sh
        container: qc.ver_gummy-violet-tamarin
timeout: 1800
