config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/I2PC/scipion-docker:
      branch: ibergrid22
      repo: https://github.com/I2PC/scipion-docker.git
    github.com/scipion-em/docs:
      branch: ibergrid22
      repo: https://github.com/scipion-em/docs.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/I2PC/scipion-docker git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-cardinal-seal.sh
        container: qc.acc_randy-mauve-cow
  QC.Doc:
    repos:
      github.com/scipion-em/docs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-cinnabar-kangaroo.sh
        container: qc.doc_paltry-chocolate-uakari
      github.com/scipion-em/docs git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-green-coral.sh
        container: qc.doc_seedy-corn-quetzal
      github.com/scipion-em/docs restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-gamboge-termite.sh
        container: qc.doc_flabby-persimmon-dachshund
  QC.Lic:
    repos:
      github.com/I2PC/scipion-docker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-sepia-loon.sh
        container: qc.lic_snippy-green-bee
  QC.Sty:
    repos:
      github.com/I2PC/scipion-docker hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-goldenrod-owl.sh
        container: qc.sty_boozy-lemon-quokka
  QC.Ver:
    repos:
      github.com/I2PC/scipion-docker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-bronze-lemur.sh
        container: qc.ver_homey-taupe-chameleon
timeout: 1800
