config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/I2PC/scipion-docker:
      branch: ibergrid22
      repo: https://github.com/I2PC/scipion-docker.git
    github.com/scipion-em/docs:
      branch: ibergrid22
      repo: https://github.com/scipion-em/docs.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/I2PC/scipion-docker git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-blue-moorhen.sh
        container: qc.acc_lovely-cream-mule
  QC.Doc:
    repos:
      github.com/scipion-em/docs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-cyan-bordeaux.sh
        container: qc.doc_zippy-goldenrod-affenpinscher
      github.com/scipion-em/docs git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-khaki-gibbon.sh
        container: qc.doc_tacky-indigo-mist
      github.com/scipion-em/docs restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-chartreuse-labradoodle.sh
        container: qc.doc_seedy-firebrick-beagle
  QC.Lic:
    repos:
      github.com/I2PC/scipion-docker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-denim-ocelot.sh
        container: qc.lic_shabby-gold-capuchin
  QC.Sty:
    repos:
      github.com/I2PC/scipion-docker hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-corn-ragdoll.sh
        container: qc.sty_zippy-buff-cockroach
  QC.Ver:
    repos:
      github.com/I2PC/scipion-docker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-white-corgi.sh
        container: qc.ver_freaky-mustard-guppy
timeout: 1800
