config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/I2PC/scipion-docker:
      branch: ibergrid22
      repo: https://github.com/I2PC/scipion-docker.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/I2PC/scipion-docker git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-plum-blue.sh
        container: qc.acc_whiny-cornflower-frog
  QC.Doc:
    repos:
      github.com/I2PC/scipion-docker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-green-salamander.sh
        container: qc.doc_grumpy-cornflower-tamarin
      github.com/I2PC/scipion-docker git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-brass-shrimp.sh
        container: qc.doc_pasty-lavender-nightingale
      github.com/I2PC/scipion-docker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-fuchsia-tzu.sh
        container: qc.doc_sleazy-maroon-alligator
  QC.Lic:
    repos:
      github.com/I2PC/scipion-docker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-amber-goose.sh
        container: qc.lic_surly-gold-markhor
  QC.Sty:
    repos:
      github.com/I2PC/scipion-docker hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-aqua-bracke.sh
        container: qc.sty_randy-dandelion-magpie
  QC.Ver:
    repos:
      github.com/I2PC/scipion-docker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-xanthic-flounder.sh
        container: qc.ver_scaly-magnolia-cockroach
timeout: 1800
