config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/I2PC/scipion-docker:
      branch: ibergrid22
      repo: https://github.com/I2PC/scipion-docker.git
    github.com/scipion-em/docs:
      branch: ibergrid22
      repo: https://github.com/scipion-em/docs.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/I2PC/scipion-docker git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-linen-weasel.sh
        container: qc.acc_lousy-seashell-weasel
  QC.Doc:
    repos:
      github.com/scipion-em/docs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-puce-akbash.sh
        container: qc.doc_grumpy-carmine-hamster
      github.com/scipion-em/docs git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-mustard-fox.sh
        container: qc.doc_hilly-heliotrope-snail
      github.com/scipion-em/docs restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-ecru-mandrill.sh
        container: qc.doc_hilly-beige-dormouse
  QC.Lic:
    repos:
      github.com/I2PC/scipion-docker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-amethyst-harrier.sh
        container: qc.lic_muzzy-olive-mole
  QC.Sty:
    repos:
      github.com/I2PC/scipion-docker hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-cream-dodo.sh
        container: qc.sty_snappy-firebrick-cassowary
  QC.Ver:
    repos:
      github.com/I2PC/scipion-docker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-orchid-heron.sh
        container: qc.ver_thirsty-taupe-macaque
timeout: 1800
